import { Router } from 'express';
import authRoutes from './auth.routes';
import tripsRoutes from './trips.routes';
import gpsRoutes from './gps.routes';
import markersRoutes from './markers.routes';
import mediaRoutes from './media.routes';
import friendsRoutes from './friends.routes';
import wishlistRoutes from './wishlist.routes';
import calendarRoutes from './calendar.routes';
import diaryRoutes from './diary.routes';
import timelineRoutes from './timeline.routes';
import poiRoutes from './poi.routes';
import notificationsRoutes from './notifications.routes';
import chatRoutes from './chat.routes';
import expensesRoutes from './expenses.routes';
import packingRoutes from './packing.routes';
import reviewsRoutes from './reviews.routes';
import favoritesRoutes from './favorites.routes';
import achievementsRoutes from './achievements.routes';
import searchRoutes from './search.routes';
import adminRoutes from './admin.routes';
import replayRoutes from './replay.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/trips', tripsRoutes);
router.use('/', gpsRoutes);
router.use('/', markersRoutes);
router.use('/', mediaRoutes);
router.use('/friends', friendsRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/calendar', calendarRoutes);
router.use('/diary', diaryRoutes);
router.use('/', timelineRoutes);
router.use('/poi', poiRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/chat', chatRoutes);
router.use('/expenses', expensesRoutes);
router.use('/packing', packingRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/favorites', favoritesRoutes);
router.use('/achievements', achievementsRoutes);
router.use('/search', searchRoutes);
router.use('/admin', adminRoutes);
router.use('/', replayRoutes);

export default router;
